[books]
title = "북저널리즘 ─ 전체"
url = "https://www.bookjournalism.com/books"
entrySelector = "div.item"
titleSelector = "span.summary"
linkSelector = "a.link-inner"
contentSelector = "span.post-title"
imageSelector = "span.cover"
waitUntil = "networkidle"

[world]
title = "북저널리즘 ─ 세계"
url = "https://www.bookjournalism.com/books/category/28927"
entrySelector = "div.item"
titleSelector = "span.summary"
linkSelector = "a.link-inner"
contentSelector = "span.post-title"
imageSelector = "span.cover"
waitUntil = "networkidle"

[tech]
title = "북저널리즘 ─ 테크"
url = "https://www.bookjournalism.com/books/category/28926"
entrySelector = "div.item"
titleSelector = "span.summary"
linkSelector = "a.link-inner"
contentSelector = "span.post-title"
imageSelector = "span.cover"
waitUntil = "networkidle"

[culture]
title = "북저널리즘 ─ 컬처"
url = "https://www.bookjournalism.com/books/category/34"
entrySelector = "div.item"
titleSelector = "span.summary"
linkSelector = "a.link-inner"
contentSelector = "span.post-title"
imageSelector = "span.cover"
waitUntil = "networkidle"

[audio]
title = "북저널리즘 ─ 오디오"
url = "https://www.bookjournalism.com/audio"
entrySelector = "div.item"
titleSelector = "span.summary"
linkSelector = "a.link-inner"
contentSelector = "span.post-title"
imageSelector = "span.cover"
waitUntil = "networkidle"

[audioclip]
title = "오디오클립 ─ 북저널리즘 라디오"
url = "https://audioclip.naver.com/channels/2939"
entrySelector = "div.end_player_list div.list_item"
titleSelector = "a.end_player_title"
linkSelector = "a.end_player_title"
contentSelector = "span.detail_playtime"
imageSelector = "img.thumb_image"
waitUntil = "networkidle"
