[books]
title = "북저널리즘 ─ 전체"
url = "https://www.bookjournalism.com/books"
entrySelector = "div.item"
titleSelector = "span.summary"
linkSelector = "a.link-inner"
contentSelector = "span.post-title"
imageSelector = "span.cover"
waitForSelector = "div.item"
onFail = "stale"

[audioclip]
title = "오디오클립 ─ 북저널리즘 라디오"
url = "https://audioclip.naver.com/channels/2939"
entrySelector = "div.end_player_list div.list_item"
titleSelector = "a.end_player_title"
linkSelector = "a.end_player_title"
contentSelector = "span.detail_playtime"
imageSelector = "img.thumb_image"
waitUntil = "networkidle"
onFail = "stale"
